src/blog/urls.py
from django.urls import path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('create', create_blog_view, name="create"),
    path('<slug>/', view_blog_detail, name="detail"),
    path('<slug>/edit', edit_blog_view, name="edit")
]

src/protest/urls.py
import statistics
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from personal.views import *
from account.views import *
from django.contrib.auth import views as auth_views

from protest.settings import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name='home'),

    path('register/', registration_view, name="register"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('must_authentication/', must_authentication_view, name="must_authentication"),

    path('account/', account_view, name="account"),
    path('blog/', include('blog.urls', "blog")),


    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
        name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('password_reset/', auth_views.PasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
        name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/personal/models.py
from django.db import models

# Priority = [
#     ("L", "low"),
#     ("M", "medium"),
#     ("H", "high"),
# ]


# class Question(models.Model):
#     title = models.CharField(max_length=60)
#     question = models.TextField(max_length=600)
#     priority = models.CharField(max_length=1, choices=Priority, default="medium")

#     def __str__(self):
#         return self.title

#     class Meta:
#         verbose_name = "The questions"
#         verbose_name_plural = "People question"

src/personal/views.py
from operator import attrgetter
from django.shortcuts import render
from blog.models import *
from blog.views import get_blog_queries
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

BLOG_POSTS_PER_PAGE = 3

# Create your views here.
def home_screen_view(request):
    
    # context = {}
    # context['string_test'] = "this is the string to test the context."
    # context['string_2'] = "this is the second string test."
    # context = {
    #     'string_test' : "this is the string to test the context.",
    #     'string_2' : "this is the second string test."
    # }
    # list_value = []
    # list_value.append("test 01")
    # list_value.append("test 02")
    # list_value.append("test 03")
    # context['list_value'] = list_value

    context = {}


    query = ""
    if request.GET:
        query = request.GET.get('q', ' ')
        context['query'] = str(query)

    blog_posts = sorted(get_blog_queries(query), key=attrgetter('date_updated'), reverse=True)

    #paginate    
    page = request.GET.get('page', 1)
    blog_posts_paginator = Paginator(blog_posts, 1)

    try:
        blog_posts = blog_posts_paginator.page(page)
    except PageNotAnInteger:
        blog_posts = blog_posts_paginator.page(1)
    except EmptyPage:
        blog_posts = blog_posts_paginator.page(blog_posts_paginator.num_pages)
    context['blog_posts'] = blog_posts

    return render(request, 'personal/home.html', context)
    

src/personal/templates/personal/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style type="text/css">

	@media (max-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}

	@media (min-width: 768px) { 
		.right-column{
			margin-left: 20px;
		}
	}

	.blog-post-container{
		margin-bottom: 20px;
		width: 100%;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}

	.left-column{
		padding:0px;
	}

	.right-column{
		padding:0px;
	}
	.lead{
		font-size: 17px;
	}
</style>


<!-- main content -->
<div class="container">
	<div class="row">

		<!-- blog feed -->
		<div class="left-column col-lg-7 offset-lg-1">

			<!-- Top 'create post' bar -->
			<div class="d-lg-none mb-3">
				<div class="card m-auto d-flex flex-column p-3">
					<img class="img-fluid d-block m-auto pb-2" src="{% static 'imgs/logo.png' %}" width="72" height="72">
					<p class="lead">In this course you'll learn how to build a simple blog with user registration and blog CRUD functionality. Django is a powerful 
	  					framework and you'll see why in this course.</p>
					<p class="m-auto"><a class="btn btn-primary" href="{% url 'blog:create' %}">Create post</a></p>
				</div>
			</div>
			<!-- end Top 'create post' bar -->

			<!-- Blog posts-->
			{% if blog_posts %}
				{% for post in blog_posts %}
					<div class="blog-post-container">
						{% if post %}
							{% include 'blog/snippets/blog_post_snippet.html' with blog_post=post %}
						{% else %}
							<div class="container">
								<div class="row">
									<div class="card m-auto">
										<div class="card-body mt-2 mb-2">
											<h2 class="card-title">No results</h2>
											<p class="card-text">There were no results matching the search: "{{query}}"</p>
										</div>
									</div>
								</div>
							</div>
						{% endif %}
					</div>
				{% endfor %}
			{% else %}
				<div class="blog-post-container">
					{% include 'blog/snippets/blog_post_snippet.html' with query=query %}
				</div>
			{% endif %}
			<!-- End Blog posts-->

			{% include 'blog/snippets/blog_post_pagination.html' with blog_posts=blog_posts  %}
		</div>
		<!-- end blog feed -->

		<!-- Right 'create post' column  -->
		<div class="right-column col-lg-3 d-lg-flex d-none flex-column">

			<div class="card create-post-bar d-flex flex-column p-3">
				<img class="img-fluid d-block m-auto pb-2" src="{% static 'imgs/logo.png' %}" width="72" height="72">
				<p class="lead">In this course you'll learn how to build a simple blog with user registration and blog CRUD functionality. Django is a powerful 
  					framework and you'll see why in this course.</p>
				<p class="m-auto"><a class="btn btn-primary" href="{% url 'blog:create' %}">Create post</a></p>
			</div>
		
		</div>
		<!-- end Right 'create post' column  -->

	</div>
</div>

{% endblock content %}